# Title
title: Создание блока

# Description (~160 symbols)
description: >
  Создание собственного блока, присвоение текстуры и добавление его в игру. Добавление в креативную вкладку.

# Contributors
contributors:
  -
    name: Ivasik
    role: Автор
    github: https://github.com/YouTy6bl4
