# Title
title: Создание предмета

# Description (~160 symbols)
description: >
  Создание собственного предмета, присвоение текстуры и добавление его в игру. Добавление в креативную вкладку.

# Contributors
contributors:
  -
    name: CMTV
    role: Автор
    github: https://github.com/CMTV
  -
    name: Ivasik
    role: Автор
    github: https://github.com/YouTy6bl4
