title: Установка программ

description: >
  Установка необходимых программ, которые необходимы для разработки Bukkit плагинов.

contributors:
  -
    name: Ivasik
    role: Автор
    github: https://github.com/YouTy6bl4
